apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    name: lasyainfy
    project: Ecoms-Jewellery
    component: Front-end
    version: "1.3"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-lb
  labels:
    name: lasyainfy
    project: Ecoms-Jewellery
    component: Front-end
    version: "1.3"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
