apiVersion: v1
kind: Pod
metadata:
  name: lakshman
  namespace: ecoms
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: ubuntu
      image: ubuntu
      command: ["sleep", "3600"]   
