apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: lasyainfy
    project: Ecoms-Jewellery
    component: Front-end
    version: "1.2"
  ports:
  -  protocol: TCP
     targetPort: 80
     nodePort: 30081
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-np
  labels:
    name: lasyainfy
    project: Ecoms-Jewellery
    component: Front-end
    version: "1.2"
spec:
  containers:
    - name: nginx
      image: nginx
     
