apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    name: lasyainfy
    project: Ecoms-Jewellery
    component: Front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: lasyainfy
    project: Ecoms-Jewellery
    component: Front-end
  # namespace: ecoms
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
